In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.2'

In [3]:
print(np.arange(10))
print(np.arange(1, 15, 3))

[0 1 2 3 4 5 6 7 8 9]
[ 1  4  7 10 13]


In [4]:
np.random.randn(3, 4)

array([[-0.50340768, -1.23552762,  0.15670766,  1.35182917],
       [-1.75607177,  0.27692648, -0.6431435 ,  0.045529  ],
       [ 0.65890354, -1.23054791, -0.97708787, -1.52821336]])